/* ── views/ClientCommon.js ────────────────────────────────────
   Shared Client UI pieces in the Atlantis (Vuetify) look.
   Templates live in index.html:
     tpl-atl-table, tpl-seafarer-profile, tpl-document-viewer

   - AtlTable               — Atlantis data table: COLUMNS visibility menu,
                              PRESETS (visual only), sortable headers, optional
                              row selection and section header rows, Atlantis
                              pagination footer, Export PDF of visible columns.
                              On phones it renders cards (title / subtitle /
                              label-value lines) with "Show more" instead.
   - SeafarerProfileDialog  — profile modal opened by setting
                              erpStore.clientUi.profileId. Only the Documents
                              tab has content (view, download, ZIP of selection).
   - DocumentViewerDialog   — "View Document" dialog with PDF preview.

   Depends on globals: erpStore, utils.js, crew.js, documents.js,
     window.jspdf (jsPDF + autotable), JSZip
   Exposes globals: AtlTable, SeafarerProfileDialog, DocumentViewerDialog,
     atlDate(), downloadBlob(), documentPdf()
──────────────────────────────────────────────────────────────── */

const ATL_MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

// '2026-10-15' → '15 Oct 2026' (Atlantis date format)
function atlDate(iso) {
    if (!iso) return '—';
    const [y, m, dd] = iso.split('-');
    return dd + ' ' + ATL_MONTHS[+m - 1] + ' ' + y;
}

function downloadBlob(blob, fileName) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = fileName;
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 2000);
}

function _slug(s) { return String(s).replace(/[^A-Za-z0-9]+/g, '_').replace(/^_|_$/g, ''); }

// Mock scan of a seafarer document as a jsPDF instance
function documentPdf(doc, s) {
    const pdf = new window.jspdf.jsPDF({ unit: 'pt', format: 'a4' });
    const W = pdf.internal.pageSize.getWidth();
    pdf.setDrawColor(21, 101, 192); pdf.setLineWidth(2);
    pdf.rect(40, 40, W - 80, 300);
    pdf.setFont('helvetica', 'bold'); pdf.setFontSize(10); pdf.setTextColor(21, 101, 192);
    pdf.text((doc.issuedBy || '').toUpperCase(), 60, 70);
    pdf.text(doc.category.toUpperCase(), W - 60, 70, { align: 'right' });
    pdf.setFontSize(20); pdf.setTextColor(33, 33, 33);
    pdf.text(pdf.splitTextToSize(doc.name, W - 120), 60, 110);
    const rows = [
        ['Holder',          s ? fullNameLF(s) : '—'],
        ['Nationality',     s ? (s.nationality || '—').toUpperCase() : '—'],
        ['Rank',            s ? s.rank.toUpperCase() : '—'],
        ['Document number', doc.number],
        ['Country',         doc.country || '—'],
        ['Issued',          atlDate(doc.issueDate)],
        ['Expires',         doc.expiryDate ? atlDate(doc.expiryDate) : 'No expiry'],
    ];
    pdf.setFontSize(11);
    rows.forEach((r, i) => {
        pdf.setFont('helvetica', 'bold');   pdf.text(r[0] + ':', 60, 160 + i * 22);
        pdf.setFont('helvetica', 'normal'); pdf.text(String(r[1]), 200, 160 + i * 22);
    });
    pdf.setFontSize(48); pdf.setTextColor(225, 225, 225); pdf.setFont('helvetica', 'bold');
    pdf.text('SAMPLE', W / 2, 520, { align: 'center', angle: 20 });
    pdf.setFontSize(8); pdf.setTextColor(140, 140, 140); pdf.setFont('helvetica', 'normal');
    pdf.text('Mockup document generated by the Client Portal mockup — not a real certificate.', 40, 800);
    return pdf;
}

// Compare for sorting: null/empty last, numbers numerically, strings naturally
function _atlCmp(a, b) {
    const ea = a == null || a === '', eb = b == null || b === '';
    if (ea || eb) return ea === eb ? 0 : (ea ? 1 : -1);
    if (typeof a === 'number' && typeof b === 'number') return a - b;
    return String(a).localeCompare(String(b), 'en', { numeric: true });
}

// ── AtlTable ──────────────────────────────────────────────────
/* columns: [{ key, title, fixed?, type?: 'link' | 'chip', format?(value, row),
              cls?(row) → class, chip?(row) → { text, color } | null }]
   items:   rows with a unique _key, optional _section, raw values per key and
            optional <key>_sort (sort value) / <key>_link === false (no link) */
const AtlTable = {
    template: '#tpl-atl-table',
    props: {
        columns:     { type: Array,   required: true },
        items:       { type: Array,   required: true },
        visible:     { type: Array,   required: true },   // v-model:visible — optional column keys shown
        sections:    { type: Array,   default: null },    // [{ id, label, icon }]
        selectable:  { type: Boolean, default: false },
        selected:    { type: Array,   default: () => [] },// v-model:selected — row _keys
        pdfTitle:    { type: String,  default: 'Export' },
        pdfSubtitle: { type: String,  default: '' },
        sortKey:     { type: String,  default: null },
        sortDesc:    { type: Boolean, default: false },
        emptyText:   { type: String,  default: 'No records found' },
    },
    emits: ['update:visible', 'update:selected', 'open', 'refresh'],

    data() {
        return { sKey: this.sortKey, sDesc: this.sortDesc, page: 1, perPage: 20, colMenu: false,
                 phoneLimit: 20 };   // phone: cards shown before "Show more"
    },

    computed: {
        shownColumns() { return this.columns.filter(c => c.fixed || this.visible.includes(c.key)); },
        colspan() {
            return this.shownColumns.length + (this.selectable ? 1 : 0) + (this.$slots['row-actions'] ? 1 : 0);
        },
        sorted() {
            const k = this.sKey, dir = this.sDesc ? -1 : 1;
            const sec = r => this.sections ? this.sections.findIndex(s => s.id === r._section) : 0;
            const val = r => (r[k + '_sort'] !== undefined ? r[k + '_sort'] : r[k]);
            return this.items
                .map((r, i) => ({ r, i }))
                .sort((a, b) => (sec(a.r) - sec(b.r)) || (k ? _atlCmp(val(a.r), val(b.r)) * dir : 0) || a.i - b.i)
                .map(x => x.r);
        },
        pageCount() { return Math.max(1, Math.ceil(this.sorted.length / this.perPage)); },
        // Page rows with section headers inserted where the section changes
        // (phone: the first phoneLimit rows instead of a page)
        pageRows() {
            const slice = this.isPhone
                ? this.sorted.slice(0, this.phoneLimit)
                : this.sorted.slice((this.page - 1) * this.perPage, this.page * this.perPage);
            if (!this.sections) return slice.map(r => ({ row: r }));
            const out = [];
            let last = null;
            slice.forEach(r => {
                if (r._section !== last) {
                    out.push({ header: this.sections.find(s => s.id === r._section) || { id: r._section, label: r._section },
                               count: this.items.filter(x => x._section === r._section).length });
                    last = r._section;
                }
                out.push({ row: r });
            });
            return out;
        },
        // Phone card layout: title = first link column (or first column), subtitle =
        // the other fixed columns, body = the visible optional columns as label / value
        cardTitleCol() { return this.shownColumns.find(c => c.type === 'link') || this.shownColumns[0]; },
        cardSubCols()  { return this.shownColumns.filter(c => c.fixed && c !== this.cardTitleCol); },
        cardBodyCols() { return this.shownColumns.filter(c => !c.fixed && c !== this.cardTitleCol); },
        rangeText() {
            const n = this.sorted.length;
            if (!n) return '0 of 0';
            const start = (this.page - 1) * this.perPage + 1;
            return start + ' to ' + Math.min(n, start + this.perPage - 1) + ' of ' + n;
        },
        pageKeys() { return this.pageRows.filter(e => e.row).map(e => e.row._key); },
        allOnPageSelected() { return this.pageKeys.length > 0 && this.pageKeys.every(k => this.selected.includes(k)); },
        someSelected() { return this.pageKeys.some(k => this.selected.includes(k)); },
    },

    watch: {
        items()   { if (this.page > this.pageCount) this.page = 1; this.phoneLimit = 20; },
        perPage() { this.page = 1; },
    },

    methods: {
        cell(col, row) {
            const v = row[col.key];
            if (col.format) return col.format(v, row);
            return v == null || v === '' ? '—' : v;
        },
        toggleSort(col) {
            if (this.sKey !== col.key) { this.sKey = col.key; this.sDesc = false; }
            else if (!this.sDesc)      { this.sDesc = true; }
            else                       { this.sKey = null; this.sDesc = false; }
        },
        toggleCol(key) {
            const on = this.visible.includes(key);
            this.$emit('update:visible', this.columns
                .filter(c => !c.fixed && (c.key === key ? !on : this.visible.includes(c.key)))
                .map(c => c.key));
        },
        showAll() { this.$emit('update:visible', this.columns.filter(c => !c.fixed).map(c => c.key)); },
        hideAll() { this.$emit('update:visible', []); },
        toggleRow(key) {
            this.$emit('update:selected', this.selected.includes(key)
                ? this.selected.filter(k => k !== key) : this.selected.concat(key));
        },
        toggleAllOnPage() {
            const keys = this.pageKeys;
            this.$emit('update:selected', this.allOnPageSelected
                ? this.selected.filter(k => !keys.includes(k))
                : this.selected.concat(keys.filter(k => !this.selected.includes(k))));
        },
        refresh() { this.page = 1; this.$emit('refresh'); },

        // PDF of all rows (not just the page) with the visible columns
        exportPdf() {
            const cols = this.shownColumns;
            const pdf = new window.jspdf.jsPDF({ orientation: cols.length > 6 ? 'landscape' : 'portrait', unit: 'pt', format: 'a4' });
            const W = pdf.internal.pageSize.getWidth(), H = pdf.internal.pageSize.getHeight();
            pdf.setFont('helvetica', 'bold'); pdf.setFontSize(15); pdf.setTextColor(21, 101, 192);
            pdf.text(this.pdfTitle, 40, 46);
            pdf.setFont('helvetica', 'normal'); pdf.setFontSize(9); pdf.setTextColor(90, 90, 90);
            pdf.text(this.pdfSubtitle, 40, 62);
            pdf.text('Generated ' + atlDate(isoDate(new Date())), W - 40, 46, { align: 'right' });
            const body = [];
            let last = null;
            this.sorted.forEach(r => {
                if (this.sections && r._section !== last) {
                    const s = this.sections.find(x => x.id === r._section) || { label: r._section };
                    body.push([{ content: s.label + '  (' + this.items.filter(x => x._section === r._section).length + ')',
                                 colSpan: cols.length,
                                 styles: { fillColor: [232, 240, 254], textColor: [21, 101, 192], fontStyle: 'bold' } }]);
                    last = r._section;
                }
                body.push(cols.map(c => {
                    const v = c.type === 'chip' ? (c.chip(r) || {}).text : this.cell(c, r);
                    return v == null ? '' : String(v);
                }));
            });
            pdf.autoTable({
                head: [cols.map(c => c.title)], body, startY: 76,
                margin: { left: 40, right: 40, bottom: 40 },
                styles: { fontSize: 8, cellPadding: 4, textColor: [33, 33, 33], lineColor: [224, 224, 224], lineWidth: 0.5 },
                headStyles: { fillColor: [245, 245, 245], textColor: [33, 33, 33], fontStyle: 'bold' },
            });
            const n = pdf.getNumberOfPages();
            for (let i = 1; i <= n; i++) {
                pdf.setPage(i); pdf.setFontSize(8); pdf.setTextColor(140, 140, 140);
                pdf.text('Client Portal — mockup', 40, H - 20);
                pdf.text('Page ' + i + ' of ' + n, W - 40, H - 20, { align: 'right' });
            }
            pdf.save(_slug(this.pdfTitle) + '.pdf');
        },
    },
};

// ── DocumentViewerDialog ──────────────────────────────────────
const DocumentViewerDialog = {
    template: '#tpl-document-viewer',
    props: {
        // record from seafarerDocuments(), or any doc-like object with its own
        // pdf() generator and statusText (e.g. a candidate CV)
        doc:       { type: Object, default: null },
        seafarer:  { type: Object, default: null },
    },
    emits: ['close'],
    data() { return { url: null }; },
    watch: {
        doc: {
            immediate: true,
            handler(doc) {
                if (this.url) URL.revokeObjectURL(this.url);
                this.url = doc ? URL.createObjectURL(this.pdf(doc).output('blob')) : null;
            },
        },
    },
    beforeUnmount() { if (this.url) URL.revokeObjectURL(this.url); },
    methods: {
        atlDate,
        pdf(doc) { return doc.pdf ? doc.pdf() : documentPdf(doc, this.seafarer); },
        statusLabel(doc) {
            if (doc.statusText) return doc.statusText;
            return { valid: 'Valid', permanent: 'Valid (no expiry)', expiring: 'Expiring soon', expired: 'Expired' }[docStatus(doc)];
        },
        download() { this.pdf(this.doc).save(this.doc.fileName); },
    },
};

// ── SeafarerProfileDialog ─────────────────────────────────────
const SeafarerProfileDialog = {
    template: '#tpl-seafarer-profile',

    data() {
        return {
            store:        erpStore,
            tab:          'documents',
            docVisible:   ['category', 'number', 'country', 'issueDate', 'expiryDate', 'issuedBy', 'status'],
            selectedDocs: [],
            viewerDoc:    null,
            zipping:      false,
        };
    },

    watch: {
        'store.clientUi.profileId'() { this.tab = 'documents'; this.selectedDocs = []; this.viewerDoc = null; },
    },

    computed: {
        open: {
            get() { return !!this.store.clientUi.profileId; },
            set(v) { if (!v) this.store.clientUi.profileId = null; },
        },
        s()        { return seafarerById(this.store.clientUi.profileId); },
        fullName() { return fullNameLF(this.s); },
        age()      { return seafarerAge(this.s); },
        tabs() {
            return [
                { id: 'personal',  label: 'Personal Data',  icon: 'mdi-account' },
                { id: 'family',    label: 'Family Details', icon: 'mdi-account-group' },
                { id: 'medical',   label: 'Medical Record', icon: 'mdi-medical-bag' },
                { id: 'documents', label: 'Documents',      icon: 'mdi-file-document-multiple' },
                { id: 'services',  label: 'Services',       icon: 'mdi-briefcase' },
                { id: 'training',  label: 'Training',       icon: 'mdi-school' },
            ];
        },
        currentTab() { return this.tabs.find(t => t.id === this.tab); },
        lastTour()   { return this.s ? lastTourOf(this.s.id) : null; },
        lastVessel() { return this.lastTour ? allVessels.find(v => v.id === this.lastTour.vesselId) : null; },
        vesselType() { return this.lastVessel ? this.lastVessel.type.toUpperCase() : null; },

        // "n/Mmo" stats — pool seafarers carry service history, crew records use their tours
        stats() {
            const s = this.s;
            const fmt = (count, months) => count + '/' + months + 'mo';
            if (s.services) {
                const tot = s.services.reduce((a, x) => ({ c: a.c + x.count, m: a.m + x.months }), { c: 0, m: 0 });
                const at = s.services.find(x => x.label === 'At Rank') || { count: 0, months: 0 };
                const off = s.services.find(x => x.label === 'As Officer');
                return { total: fmt(tot.c, tot.m), atRank: fmt(at.count, at.months), asOfficer: off ? fmt(off.count, off.months) : null };
            }
            const months = t => Math.round(daysB(d(t.embark), d(t.current ? isoDate(TODAY) : t.signoff)) / 30.44);
            const tours = seafarerTours(s.id);
            const sum = list => fmt(list.length, list.reduce((n, t) => n + months(t), 0));
            return { total: sum(tours), atRank: sum(tours.filter(t => t.rank === s.rank)), asOfficer: null };
        },
        statusLine() {
            const cid = dedicatedClientOf(this.s.id);
            const c = allClientsData.find(x => x.id === cid);
            const where = this.lastTour && this.lastTour.current
                ? 'On Board ' + this.lastVessel.name.toUpperCase() : 'On Vacation';
            return (c ? 'Dedicated to ' + c.name.toUpperCase() + ' - ' : '') + where;
        },

        docColumns() {
            const expCls = r => ({ expired: 'atl-text-error', expiring: 'atl-text-warning' })[r.statusId] || '';
            return [
                { key: 'type',       title: 'Document Type', fixed: true, type: 'link' },
                { key: 'category',   title: 'Document Category' },
                { key: 'number',     title: 'Document Number' },
                { key: 'country',    title: 'Country' },
                { key: 'issueDate',  title: 'Issued Date',     format: v => atlDate(v) },
                { key: 'expiryDate', title: 'Expiration Date', format: v => v ? atlDate(v) : '—', cls: expCls },
                { key: 'issuedBy',   title: 'Issued By' },
                { key: 'status',     title: 'Status', type: 'chip', chip: r => r.statusChip },
                { key: 'holder',     title: 'Seafarer Name' },
            ];
        },
        docRows() {
            if (!this.s) return [];
            return seafarerDocuments(this.s.id).map(doc => {
                const st = docStatus(doc);
                return {
                    _key: doc.id, doc, type: doc.name, category: doc.category, number: doc.number,
                    country: doc.country, issueDate: doc.issueDate, expiryDate: doc.expiryDate,
                    issuedBy: doc.issuedBy, holder: this.s.name, statusId: st,
                    status: st,
                    statusChip: { valid:     { text: 'Valid',    color: 'success' },
                                  permanent: { text: 'Valid',    color: 'success' },
                                  expiring:  { text: 'Expiring', color: 'warning' },
                                  expired:   { text: 'Expired',  color: 'error' } }[st],
                };
            });
        },
    },

    methods: {
        viewDoc(row)     { this.viewerDoc = row.doc; },
        downloadDoc(row) { documentPdf(row.doc, this.s).save(row.doc.fileName); },
        async downloadSelected() {
            this.zipping = true;
            try {
                const zip = new JSZip();
                this.docRows.filter(r => this.selectedDocs.includes(r._key))
                    .forEach(r => zip.file(r.doc.fileName, documentPdf(r.doc, this.s).output('arraybuffer')));
                const blob = await zip.generateAsync({ type: 'blob' });
                downloadBlob(blob, _slug(this.s.lastName || this.s.name) + '_documents.zip');
            } finally {
                this.zipping = false;
            }
        },
    },
};
